### ISSUE TITLE
It doesn't work with gradle 4.7

### ISSUE THREAD

**Issue by sinwe** [gradle/gradle-hazelcast-plugin#1]
Is this project still maintained?

I got the following error with gradle 4.7

   > Failed to apply plugin [class 'org.gradle.caching.hazelcast.HazelcastPlugin']                                                                     
   > org.gradle.api.internal.project.DefaultProject_Decorated cannot be cast to org.gradle.api.initialization.Settings

**Comment by sinwe** [comment]
@lptr Is this repo still maintained? The last commit was July 2017.
Furthermore, this doesn't work with gradle 4.7 and has issue finding the correct plugin class. I have the fix and enhancement to support multiple hazelcast node as well.

**Comment by lptr** [comment]
Hi @sinwe, sorry for the late reply. Would you mind contributing the fix and the enhancement in two separate PRs maybe?

**Comment by sinwe** [comment]
@lptr I just raise PR to fix the issue

**Comment by sinwe** [comment]
@lptr do you mind to look at the PR?

**Comment by lptr** [comment]
Should be fixed by #3. Thanks @sinwe!
